[project]
name = "pybricks"
version = "3.6.1"
description = "Documentation and user-API stubs for Pybricks MicroPython"
authors = [{ name = "The Pybricks Authors", email = "team@pybricks.com" }]
requires-python = ">=3.8, <4.0"
readme = "README.rst"
license = "MIT"
maintainers = [
    { name = "Laurens Valk", email = "laurens@pybricks.com" },
    { name = "David Lechner", email = "david@pybricks.com" },
]
classifiers = ["Programming Language :: Python :: Implementation :: MicroPython"]
dependencies = [
    "sphinx-design>=0.5.0",
]

[project.urls]
Homepage = "https://pybricks.com"
Repository = "https://github.com/pybricks/pybricks-api"
Documentation = "https://docs.pybricks.com"

[dependency-groups]
lint = [
    "black>=22.3.0,<23",
    "doc8>=0.8.1,<0.9",
    "flake8~=4.0",
]
doc = [
    "Sphinx",
    "sphinx-rtd-theme>=1.0.0,<2",
    "toml>=0.10.0,<0.11",
]

[tool.uv]
default-groups = [
    "lint",
    "doc",
]

[tool.uv.sources]
Sphinx = { git = "https://github.com/pybricks/sphinx.git", rev = "cd277d09" }

[tool.hatch.build.targets.sdist]
include = [
    "src/pybricks",
    "src/micropython",
    "src/uerrno",
    "src/uio",
    "src/ujson",
    "src/umath",
    "src/urandom",
    "src/uselect",
    "src/ustruct",
    "src/usys",
]

[tool.hatch.build.targets.wheel]
include = [
    "src/pybricks",
    "src/micropython",
    "src/uerrno",
    "src/uio",
    "src/ujson",
    "src/umath",
    "src/urandom",
    "src/uselect",
    "src/ustruct",
    "src/usys",
]

[tool.hatch.build.targets.wheel.sources]
"src/pybricks" = "pybricks"
"src/micropython" = "micropython"
"src/uerrno" = "uerrno"
"src/uio" = "uio"
"src/ujson" = "ujson"
"src/umath" = "umath"
"src/urandom" = "urandom"
"src/uselect" = "uselect"
"src/ustruct" = "ustruct"
"src/usys" = "usys"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
